CONFIG_NAME: withdrawals
PRESET_BASE: mainnet

# Genesis
GENESIS_FORK_VERSION: 0x20000089
# Altair
ALTAIR_FORK_EPOCH: 1
ALTAIR_FORK_VERSION: 0x20000090
# Merge
BELLATRIX_FORK_EPOCH: 2
BELLATRIX_FORK_VERSION: 0x20000091
TERMINAL_TOTAL_DIFFICULTY: 330
# Capella
CAPELLA_FORK_EPOCH: 3
CAPELLA_FORK_VERSION: 0x20000092
MAX_WITHDRAWALS_PER_PAYLOAD: 16
# Time parameters
SECONDS_PER_SLOT: 12
SLOTS_PER_EPOCH: 32
# Deposit contract
DEPOSIT_CONTRACT_ADDRESS: 0x4242424242424242424242424242424242424242

# Lighthouse required fields..
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 512
GENESIS_DELAY: 0
SECONDS_PER_ETH1_BLOCK: 12
MIN_VALIDATOR_WITHDRAWABILITY_DELAY: 256
SHARD_COMMITTEE_PERIOD: 64
ETH1_FOLLOW_DISTANCE: 16
INACTIVITY_SCORE_BIAS: 4
INACTIVITY_SCORE_RECOVERY_RATE: 16
EJECTION_BALANCE: 16000000000
MIN_PER_EPOCH_CHURN_LIMIT: 4
CHURN_LIMIT_QUOTIENT: 32
DEPOSIT_CHAIN_ID: 32382
DEPOSIT_NETWORK_ID: 32382

# Params below are set by the script
MIN_GENESIS_TIME: TBD

